# Use an official Java runtime as the base image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /demo

# Copy the JAR file generated by Gradle into the container
COPY build/libs/backend-0.0.1-SNAPSHOT.jar backend.jar

# Expose the port your application will run on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "backend.jar"]
